### ISSUE TITLE
Gender is slightly off for some people

### ISSUE THREAD

**Issue by cloveras** [DNBbank/dnbtestdata#7]
Arne is female .. or _is_ he?

```
$ create_people.py -n 1
[
  {
    "ssn": "01037843751",
    "firstName": "Arne",
    "lastName": "Edvardsen",
    "dateOfBirth": "1978-03-01",
    "gender": "Female",
    "nationality": "Norwegian",
    "address": {
      "street": "Evensengropa 00",
      "postalCode": "8187",
      "city": "Haugland",
      "country": "NO"
    },
    "phoneNumber": "92395941",
    "email": "edvardsen1978@example.com",
    "idType": "passport"
  }
]
```

I made a branch and tried to make a PR, but it seems I lack permissions*. So, here's a new `_NorwegianName` for models/person/elements/name.py that does not always select male names:

```
class _NorwegianName:
    fake = Faker('no_NO')

    @classmethod
    def generate_random_first_name(cls, gender):
        if gender == gender.MALE:
            return cls.fake.first_name_male()
        elif gender == gender.FEMALE:
            return cls.fake.first_name_female()
        else:
            raise Exception()

    @classmethod
    def generate_random_last_name(cls):
        return cls.fake.last_name()
```

*: Permission error:

```
$  git push --set-upstream origin not-all-arnes-are-female
remote: Permission to DNBbank/dnbtestdata.git denied to cloveras.
fatal: unable to access 'https://github.com/DNBbank/dnbtestdata.git/': The requested URL returned error: 403
```

**Comment by tommythorsen** [comment]
@cloveras Did you just clone the repo, make a new branch, and then try to push it? That would probably not work, as you don't have access to write to this repo. Instead, I think it would work if you forked the repo, developed the change in your fork, and then made the pull request from there. That should be the standard workflow anyway.

Also, this is 2018. Gender is a state of mind now. Who are we to judge Arne's choice of gender?

**Comment by cloveras** [comment]
So that's it then? _I'm *out*?!_ 

Yes, should have forked, but was in a hurry, and also a bit lazy.

Hope Arne will be happy with this being fixed manually!

**Comment by cloveras** [comment]
PR: https://github.com/DNBbank/dnbtestdata/pull/10
